"""Check for changes

Revision ID: 006c63a08e58
Revises: ff05ba29f709
Create Date: 2023-05-04 10:04:21.859619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006c63a08e58'
down_revision = 'ff05ba29f709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
