"""Make pokemon_type optional in type_slot

Revision ID: 0578ad07bffc
Revises: 006c63a08e58
Create Date: 2023-05-04 10:58:11.475860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0578ad07bffc'
down_revision = '006c63a08e58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('type_slots', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('type_slots', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
