"""Starting over (autogenerated)

Revision ID: 2bc9b00559d5
Revises: 
Create Date: 2023-05-03 17:58:52.737618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc9b00559d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front_default', sa.String(), nullable=True),
    sa.Column('front_female', sa.String(), nullable=True),
    sa.Column('front_shiny', sa.String(), nullable=True),
    sa.Column('front_shiny_female', sa.String(), nullable=True),
    sa.Column('back_default', sa.String(), nullable=True),
    sa.Column('back_female', sa.String(), nullable=True),
    sa.Column('back_shiny', sa.String(), nullable=True),
    sa.Column('back_shiny_female', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprites_id'), 'sprites', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_id'), 'types', ['id'], unique=False)
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sprites_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('order', sa.Float(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sprites_id'], ['sprites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_id'), 'pokemon', ['id'], unique=False)
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abilities_id'), 'abilities', ['id'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move', sa.String(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moves_id'), 'moves', ['id'], unique=False)
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('base_stat', sa.Float(), nullable=True),
    sa.Column('effort', sa.Float(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_id'), 'stats', ['id'], unique=False)
    op.create_table('type_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_type_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['pokemon_type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_slots_id'), 'type_slots', ['id'], unique=False)
    op.create_table('version_group_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_learn_method', sa.String(), nullable=True),
    sa.Column('version_group', sa.String(), nullable=True),
    sa.Column('level_learned_at', sa.Integer(), nullable=True),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_group_details_id'), 'version_group_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_group_details_id'), table_name='version_group_details')
    op.drop_table('version_group_details')
    op.drop_index(op.f('ix_type_slots_id'), table_name='type_slots')
    op.drop_table('type_slots')
    op.drop_index(op.f('ix_stats_id'), table_name='stats')
    op.drop_table('stats')
    op.drop_index(op.f('ix_moves_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_abilities_id'), table_name='abilities')
    op.drop_table('abilities')
    op.drop_index(op.f('ix_pokemon_id'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_index(op.f('ix_types_id'), table_name='types')
    op.drop_table('types')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sprites_id'), table_name='sprites')
    op.drop_table('sprites')
    # ### end Alembic commands ###
