"""Made some fields nullable

Revision ID: bc9269a7dbb8
Revises: 2bc9b00559d5
Create Date: 2023-05-04 08:21:56.814648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9269a7dbb8'
down_revision = '2bc9b00559d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abilities', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('moves', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pokemon', 'sprites_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stats', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pokemon', 'sprites_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('moves', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('abilities', 'pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
