"""Added slot field to type_slot

Revision ID: c2af34fb3294
Revises: bc9269a7dbb8
Create Date: 2023-05-04 08:48:31.495903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2af34fb3294'
down_revision = 'bc9269a7dbb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_slots', sa.Column('slot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_slots', 'slot')
    # ### end Alembic commands ###
