"""Made move_id optional in version_group_detail

Revision ID: d9e78729d6f8
Revises: 0578ad07bffc
Create Date: 2023-05-04 11:27:19.444425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e78729d6f8'
down_revision = '0578ad07bffc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version_group_details', 'move_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version_group_details', 'move_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
