"""Check for changes

Revision ID: ff05ba29f709
Revises: c2af34fb3294
Create Date: 2023-05-04 10:04:07.253452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff05ba29f709'
down_revision = 'c2af34fb3294'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
