services:
  pokedex_backend:
    build: ./backend
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./backend/src
        target: /home
    ports:
      - "8000:8000"
  pokedex_database:
    build: ./database
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./database/src
        target: /home
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: pikachu
      POSTGRES_DB: pokedex
      PGDATA: /home/data/pgdata
      POSTGRES_HOST: 0.0.0.0